import express from 'express';
import Razorpay from 'razorpay';
import crypto from 'crypto';
import axios from 'axios';
import { db } from '../firebase.js';
import { config } from '../config.js';
import { authenticate } from '../middleware/auth.js';

const router = express.Router();
const razorpay = new Razorpay({
  key_id: config.razorpay.keyId,
  key_secret: config.razorpay.keySecret
});

// Create order
router.post('/create-order', authenticate, async (req, res) => {
  try {
    const { amount, birth_data } = req.body;
    
    // Create Razorpay order
    const options = {
      amount: amount * 100,
      currency: 'INR',
      receipt: `order_${Date.now()}`
    };
    
    const razorpayOrder = await razorpay.orders.create(options);
    
    // Save order to Firestore
    const orderRef = await db.collection('orders').add({
      userId: req.user.id,
      razorpayOrderId: razorpayOrder.id,
      amount,
      status: 'created',
      birthData: birth_data,
      createdAt: new Date().toISOString()
    });
    
    res.json({
      order_id: orderRef.id,
      razorpay_order_id: razorpayOrder.id,
      amount,
      key: config.razorpay.keyId
    });
  } catch (error) {
    console.error('Create order error:', error);
    res.status(400).json({
      error: 'Failed to create payment order',
      message: error.message
    });
  }
});

// Verify payment
router.post('/verify', authenticate, async (req, res) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature, order_id } = req.body;
    
    // Verify signature
    const sign = razorpay_order_id + '|' + razorpay_payment_id;
    const expectedSign = crypto
      .createHmac('sha256', config.razorpay.keySecret)
      .update(sign.toString())
      .digest('hex');
    
    if (razorpay_signature !== expectedSign) {
      return res.status(400).json({ error: 'Invalid payment signature' });
    }
    
    // Update order
    const orderRef = db.collection('orders').doc(order_id);
    const orderDoc = await orderRef.get();
    
    if (!orderDoc.exists) {
      return res.status(404).json({ error: 'Order not found' });
    }
    
    await orderRef.update({
      razorpayPaymentId: razorpay_payment_id,
      razorpaySignature: razorpay_signature,
      status: 'paid',
      paidAt: new Date().toISOString()
    });
    
    // Generate report
    const orderData = orderDoc.data();
    //const reportId = await generateReport(req.user.id, order_id, orderData.birthData);
    const reportId = await generateReport(
  req.user.id,
  order_id,
  orderData.birthData
  
);

// 🔥 REPORT FETCH KARO
/* const reportDoc = await db.collection('reports').doc(reportId).get();
const reportData = reportDoc.data(); */

    res.json({
     success: true,
  message: 'Payment verified successfully',
  report_id: reportId,
  status: 'processing'
    });
  } catch (error) {
    console.error('Verify payment error:', error);
    res.status(500).json({ error: 'Payment verification failed' });
  }
});

// Generate astrology report
async function generateReport(userId, orderId, birthData) {
  const reportRef = await db.collection('reports').add({
    userId,
    orderId,
    birthData,
    status: 'processing',
    createdAt: new Date().toISOString()
  });
  
  try {
    // Call DivineAPI
    const response = await axios.post(config.divineApi.url, {
      api_key: config.divineApi.key,
      //...birthData
      // Birth details
      full_name: birthData.full_name,
      day: Number(birthData.day),
      month: Number(birthData.month),
      year: Number(birthData.year),
      hour: Number(birthData.hour),
      min: Number(birthData.min),
      sec: Number(birthData.sec || 0),
      gender: birthData.gender,
      place: birthData.place,
      lat: Number(birthData.lat),
      lon: Number(birthData.lon),
      tzone: Number(birthData.tzone),
      lan: "en",

      // Company details (MANDATORY)
      company_name: "AstroMate24",
      company_url: "https://astromate24.com",
      company_email: "support@astromate24.com",
      company_mobile: "+91 8950115607",
      company_bio: "AstroMate24 provides authentic Vedic astrology reports.",
      logo_url: "https://astromate24.com/logo.png",
      footer_text: "Generated by AstroMate24",

      // UI / Theme
      text_primary_color: "#000000",
      text_secondary_color: "#7b1300",
      background_color: "#ffffff",
      theme_color: "#ebab3d",
      heading_color: "#800000",

      front_image: "https://reports.divinestore.net/public/assets/img/002/cover.png",
      report_name: "Personal Kundli Report"
    },
  {
    headers: {
      Authorization: `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXN0cm9hcGktMS5kaXZpbmVhcGkuY29tL2FwaS9hdXRoLWFwaS11c2VyIiwiaWF0IjoxNzQ0MzQ4MDM0LCJuYmYiOjE3NDQzNDgwMzQsImp0aSI6InlEMHF2akkwNkJNQXlNYkYiLCJzdWIiOiIzNTMyIiwicHJ2IjoiZTZlNjRiYjBiNjEyNmQ3M2M2Yjk3YWZjM2I0NjRkOTg1ZjQ2YzlkNyJ9.0Id-QVFmW5hn1SPmFBTqzjgd0THvHObCuLmKfm6KtW0`,
      "Content-Type": "application/json"
    }
  }
);
    
    // Update report with API response
    await reportRef.update({
      apiResponse: response.data,
      status: 'completed',
      completedAt: new Date().toISOString()
    });
  } catch (error) {
    console.error('Report generation error:', error);
    await reportRef.update({
      status: 'failed',
      error: error.response?.data || error.message
    });
  }
  
  return reportRef.id;
}

export default router;
